from __future__ import annotations

from pydantic import BaseModel, Field


class GeneratedFileChange(BaseModel):
    """
    One file modification generated by the LLM.
    """

    path: str = Field(
        min_length=1,
        description="Repository-relative file path.",
    )

    proposed_content: str = Field(
        description=(
            "Complete proposed content of the file. "
            "Do not return a partial snippet."
        ),
    )

    reason: str = Field(
        min_length=1,
        description=(
            "Short explanation of why this file "
            "needs to change."
        ),
    )


class PatchGenerationResponse(BaseModel):
    """
    Structured response returned by the LLM.
    """

    description: str = Field(
        min_length=1,
        description=(
            "Short description of the complete "
            "code change."
        ),
    )

    changes: list[GeneratedFileChange] = Field(
        default_factory=list,
        description=(
            "Files that should be modified."
        ),
    )